name: Hourly Top Posts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      ORIGIN_HOST: ${{ secrets.ORIGIN_HOST }}
      TILDA_FEED_UIDS: ${{ secrets.TILDA_FEED_UIDS }}
      TILDA_SIZE: ${{ vars.TILDA_SIZE || '100' }}
      TILDA_CONCURRENCY: ${{ vars.TILDA_CONCURRENCY || '2' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.2.1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Fetch top posts
        run: poetry run askbrain-cli fetch-top

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add -f data/top_posts.json data/top_posts_meta.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update top posts"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Prepare pages artifacts
        run: |
          mkdir -p public
          cp data/top_posts.json public/
          cp data/top_posts_meta.json public/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

