name: Hourly Top Posts

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ORIGIN_HOST: ${{ secrets.ORIGIN_HOST }}
      TILDA_FEED_UIDS: ${{ secrets.TILDA_FEED_UIDS }}
      TILDA_SIZE: ${{ vars.TILDA_SIZE || '100' }}
      TILDA_CONCURRENCY: ${{ vars.TILDA_CONCURRENCY || '2' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.2.1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Fetch top posts
        run: poetry run askbrain-cli fetch-top

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add data/top_posts.json data/top_posts_meta.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update top posts"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ github.token }}

